/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import javax.swing.JFrame;
import login.login;
import Order.order;
import Order.order2;

/**
 *
 * @author ronia
 */
public class menu extends javax.swing.JFrame {

    private String user_name;
    
    order orderFrame = new order();
    order2 orderFrame2 = new order2();

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        tpaneMenu.setBackground(new java.awt.Color(150,100,100,80));
        panelMenu.setBackground(new java.awt.Color(255,255,204,80));
        panelCOFFEEMenu.setBackground(new java.awt.Color(255,255,204,80));
        panelTEAMenu.setBackground(new java.awt.Color(255,255,204,80));
        panelPASTRYMenu.setBackground(new java.awt.Color(255,255,204,80));
    }

     public void setUserName(String userName) {
        this.user_name = userName;
        lWELCOME.setText("WELCOME " + userName + " TO CPR COFFEE & TEA SHOP!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuPanel1 = new javax.swing.JPanel();
        lWELCOME = new javax.swing.JLabel();
        lPLEASE = new javax.swing.JLabel();
        jMenuPanel2 = new javax.swing.JPanel();
        tpaneMenu = new javax.swing.JTabbedPane();
        panelMenu = new javax.swing.JPanel();
        btnTea = new javax.swing.JButton();
        btnCoffee = new javax.swing.JButton();
        btnPastry = new javax.swing.JButton();
        labelCoffee = new javax.swing.JLabel();
        labelTea = new javax.swing.JLabel();
        labelPastry = new javax.swing.JLabel();
        btnCART = new javax.swing.JButton();
        labelMenu = new javax.swing.JLabel();
        btnCHKStocks = new javax.swing.JButton();
        panelCOFFEEMenu = new javax.swing.JPanel();
        btnCoffee1 = new javax.swing.JButton();
        btnCoffee2 = new javax.swing.JButton();
        btnCoffee3 = new javax.swing.JButton();
        btnCoffee4 = new javax.swing.JButton();
        btnCoffee5 = new javax.swing.JButton();
        btnCoffee6 = new javax.swing.JButton();
        labelESPRESSO = new javax.swing.JLabel();
        labelMOCHA = new javax.swing.JLabel();
        labelAMERICANO = new javax.swing.JLabel();
        labelMACCHIATO = new javax.swing.JLabel();
        labelCAPPUCCINO = new javax.swing.JLabel();
        labelLATTE = new javax.swing.JLabel();
        btnBACK1 = new javax.swing.JButton();
        btnCART1 = new javax.swing.JButton();
        priceCOF1 = new javax.swing.JLabel();
        priceCOF2 = new javax.swing.JLabel();
        priceCOF3 = new javax.swing.JLabel();
        priceCOF5 = new javax.swing.JLabel();
        priceCOF6 = new javax.swing.JLabel();
        priceCOF4 = new javax.swing.JLabel();
        panelTEAMenu = new javax.swing.JPanel();
        btnTea1 = new javax.swing.JButton();
        btnTea2 = new javax.swing.JButton();
        btnTea3 = new javax.swing.JButton();
        btnTea4 = new javax.swing.JButton();
        btnTea5 = new javax.swing.JButton();
        btnTea6 = new javax.swing.JButton();
        labelBLACK = new javax.swing.JLabel();
        labelGREEN = new javax.swing.JLabel();
        labelSTRAWBERRY = new javax.swing.JLabel();
        labelGINGER = new javax.swing.JLabel();
        labelLEMON = new javax.swing.JLabel();
        labelMINT = new javax.swing.JLabel();
        btnBACK2 = new javax.swing.JButton();
        btnCART2 = new javax.swing.JButton();
        priceTEA1 = new javax.swing.JLabel();
        priceTEA2 = new javax.swing.JLabel();
        priceTEA3 = new javax.swing.JLabel();
        priceTEA4 = new javax.swing.JLabel();
        priceTEA5 = new javax.swing.JLabel();
        priceTEA6 = new javax.swing.JLabel();
        panelPASTRYMenu = new javax.swing.JPanel();
        btnPastry1 = new javax.swing.JButton();
        btnPastry2 = new javax.swing.JButton();
        btnPastry3 = new javax.swing.JButton();
        btnPastry4 = new javax.swing.JButton();
        btnPastry5 = new javax.swing.JButton();
        btnPastry6 = new javax.swing.JButton();
        labelCROSSAINT = new javax.swing.JLabel();
        labelMUFFIN = new javax.swing.JLabel();
        labelTART = new javax.swing.JLabel();
        labelCOOKIE = new javax.swing.JLabel();
        labelBROWNIES = new javax.swing.JLabel();
        labelCINROLL = new javax.swing.JLabel();
        btnCART3 = new javax.swing.JButton();
        btnBACK3 = new javax.swing.JButton();
        pricePTY1 = new javax.swing.JLabel();
        pricePTY2 = new javax.swing.JLabel();
        pricePTY3 = new javax.swing.JLabel();
        pricePTY4 = new javax.swing.JLabel();
        pricePTY5 = new javax.swing.JLabel();
        pricePTY6 = new javax.swing.JLabel();
        panelCART = new javax.swing.JPanel();
        btnBACK4 = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lWELCOME.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        lWELCOME.setText("WELCOME TO CPR COFFEE & TEA SHOP!");

        lPLEASE.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lPLEASE.setText("PLEASE SELECT YOUR ORDER.");

        javax.swing.GroupLayout jMenuPanel1Layout = new javax.swing.GroupLayout(jMenuPanel1);
        jMenuPanel1.setLayout(jMenuPanel1Layout);
        jMenuPanel1Layout.setHorizontalGroup(
            jMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanel1Layout.createSequentialGroup()
                .addGroup(jMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMenuPanel1Layout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(lPLEASE))
                    .addGroup(jMenuPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(lWELCOME)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMenuPanel1Layout.setVerticalGroup(
            jMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lWELCOME, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPLEASE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jMenuPanel2Layout = new javax.swing.GroupLayout(jMenuPanel2);
        jMenuPanel2.setLayout(jMenuPanel2Layout);
        jMenuPanel2Layout.setHorizontalGroup(
            jMenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2994, Short.MAX_VALUE)
        );
        jMenuPanel2Layout.setVerticalGroup(
            jMenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );

        tpaneMenu.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        btnTea.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\taevertical (1).jpg")); // NOI18N
        btnTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeaActionPerformed(evt);
            }
        });

        btnCoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\coffee-vertical (2).jpg")); // NOI18N
        btnCoffee.setBorder(null);
        btnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffeeActionPerformed(evt);
            }
        });

        btnPastry.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\pasvert (1).jpg")); // NOI18N
        btnPastry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastryActionPerformed(evt);
            }
        });

        labelCoffee.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelCoffee.setText("COFFEE");

        labelTea.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelTea.setText("TEA");

        labelPastry.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelPastry.setText("PASTRY");

        btnCART.setBackground(new java.awt.Color(255, 153, 51));
        btnCART.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\CART (2).jpg")); // NOI18N
        btnCART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCARTActionPerformed(evt);
            }
        });

        labelMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelMenu.setText("MENU");

        btnCHKStocks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCHKStocks.setForeground(new java.awt.Color(0, 102, 51));
        btnCHKStocks.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\lists.png")); // NOI18N
        btnCHKStocks.setText("CHECK STOCKS");
        btnCHKStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCHKStocksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(labelCoffee)
                        .addGap(362, 362, 362)
                        .addComponent(labelTea)
                        .addGap(372, 372, 372)
                        .addComponent(labelPastry))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(btnPastry, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCHKStocks)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(labelMenu)
                        .addGap(612, 612, 612)
                        .addComponent(btnCART, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCART, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelMenu)))
                .addGap(83, 83, 83)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPastry, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoffee)
                    .addComponent(labelTea)
                    .addComponent(labelPastry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCHKStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        tpaneMenu.addTab("MENU", panelMenu);

        btnCoffee1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-espresso-100.png")); // NOI18N
        btnCoffee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffee1ActionPerformed(evt);
            }
        });

        btnCoffee2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-coffee-cup-100.png")); // NOI18N
        btnCoffee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffee2ActionPerformed(evt);
            }
        });

        btnCoffee3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-macchiato-100.png")); // NOI18N
        btnCoffee3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffee3ActionPerformed(evt);
            }
        });

        btnCoffee4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-cappuccino-100.png")); // NOI18N
        btnCoffee4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffee4ActionPerformed(evt);
            }
        });

        btnCoffee5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-latte-100.png")); // NOI18N
        btnCoffee5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffee5ActionPerformed(evt);
            }
        });

        btnCoffee6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-cappuccino-100 (1).png")); // NOI18N
        btnCoffee6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffee6ActionPerformed(evt);
            }
        });

        labelESPRESSO.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelESPRESSO.setText("ESPRESSO");

        labelMOCHA.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelMOCHA.setText("MOCHA");

        labelAMERICANO.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelAMERICANO.setText("AMERICANO");

        labelMACCHIATO.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelMACCHIATO.setText("MACCHIATO");

        labelCAPPUCCINO.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelCAPPUCCINO.setText("CAPPUCCINO");

        labelLATTE.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelLATTE.setText("LATTE");

        btnBACK1.setBackground(new java.awt.Color(51, 153, 255));
        btnBACK1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBACK1.setText("BACK");
        btnBACK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACK1ActionPerformed(evt);
            }
        });

        btnCART1.setBackground(new java.awt.Color(255, 153, 51));
        btnCART1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\CART (2).jpg")); // NOI18N
        btnCART1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCART1ActionPerformed(evt);
            }
        });

        priceCOF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceCOF1.setText("₱ 60.25");

        priceCOF2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceCOF2.setText("₱ 63.50");

        priceCOF3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceCOF3.setText("₱ 65.00");

        priceCOF5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceCOF5.setText("₱ 68.25");

        priceCOF6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceCOF6.setText("₱ 67.75");

        priceCOF4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceCOF4.setText("₱ 60.50");

        javax.swing.GroupLayout panelCOFFEEMenuLayout = new javax.swing.GroupLayout(panelCOFFEEMenu);
        panelCOFFEEMenu.setLayout(panelCOFFEEMenuLayout);
        panelCOFFEEMenuLayout.setHorizontalGroup(
            panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCOFFEEMenuLayout.createSequentialGroup()
                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCoffee4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCoffee1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                                .addComponent(btnCoffee2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(btnCoffee3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                                .addComponent(btnCoffee5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCoffee6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                    .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCAPPUCCINO)
                            .addComponent(priceCOF4))
                        .addGap(366, 366, 366)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLATTE)
                            .addComponent(priceCOF5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAMERICANO)
                            .addComponent(priceCOF6))
                        .addGap(143, 143, 143)))
                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCART1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBACK1))
                .addGap(150, 150, 150))
            .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelESPRESSO)
                    .addComponent(priceCOF1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMOCHA)
                    .addComponent(priceCOF2))
                .addGap(357, 357, 357)
                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMACCHIATO)
                    .addComponent(priceCOF3))
                .addGap(378, 378, 378))
        );
        panelCOFFEEMenuLayout.setVerticalGroup(
            panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCoffee2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCoffee1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCoffee3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelESPRESSO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMOCHA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceCOF1)
                                    .addComponent(priceCOF2)))
                            .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                                .addComponent(labelMACCHIATO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceCOF3)))
                        .addGap(32, 32, 32)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCoffee5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCoffee4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCoffee6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCAPPUCCINO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLATTE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAMERICANO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCOFFEEMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceCOF4)
                            .addComponent(priceCOF5)
                            .addComponent(priceCOF6))
                        .addGap(62, 62, 62))
                    .addGroup(panelCOFFEEMenuLayout.createSequentialGroup()
                        .addComponent(btnCART1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                        .addComponent(btnBACK1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );

        tpaneMenu.addTab("COFFEE", panelCOFFEEMenu);

        btnTea1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-black-tea-100.png")); // NOI18N
        btnTea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTea1ActionPerformed(evt);
            }
        });

        btnTea2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-teacup-without-handle-100.png")); // NOI18N
        btnTea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTea2ActionPerformed(evt);
            }
        });

        btnTea3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-ginger-100.png")); // NOI18N
        btnTea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTea3ActionPerformed(evt);
            }
        });

        btnTea4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-lemon-100.png")); // NOI18N
        btnTea4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTea4ActionPerformed(evt);
            }
        });

        btnTea5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-mint-tea-100.png")); // NOI18N
        btnTea5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTea5ActionPerformed(evt);
            }
        });

        btnTea6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-strawberry-100.png")); // NOI18N
        btnTea6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTea6ActionPerformed(evt);
            }
        });

        labelBLACK.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelBLACK.setText("BLACK TEA");

        labelGREEN.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelGREEN.setText("GREEN TEA");

        labelSTRAWBERRY.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelSTRAWBERRY.setText("STRAWBERRY TEA");

        labelGINGER.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelGINGER.setText("GINGER TEA");

        labelLEMON.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelLEMON.setText("LEMON TEA");

        labelMINT.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelMINT.setText("MINT TEA");

        btnBACK2.setBackground(new java.awt.Color(51, 153, 255));
        btnBACK2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBACK2.setText("BACK");
        btnBACK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACK2ActionPerformed(evt);
            }
        });

        btnCART2.setBackground(new java.awt.Color(255, 153, 51));
        btnCART2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\CART (2).jpg")); // NOI18N
        btnCART2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCART2ActionPerformed(evt);
            }
        });

        priceTEA1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceTEA1.setText("₱ 45.25");

        priceTEA2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceTEA2.setText("₱ 49.50");

        priceTEA3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceTEA3.setText("₱ 50.25");

        priceTEA4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceTEA4.setText("₱ 53.50");

        priceTEA5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceTEA5.setText("₱ 55.75");

        priceTEA6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceTEA6.setText("₱ 60.50");

        javax.swing.GroupLayout panelTEAMenuLayout = new javax.swing.GroupLayout(panelTEAMenu);
        panelTEAMenu.setLayout(panelTEAMenuLayout);
        panelTEAMenuLayout.setHorizontalGroup(
            panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTEAMenuLayout.createSequentialGroup()
                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTEAMenuLayout.createSequentialGroup()
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTEAMenuLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTea4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTea1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(174, 174, 174)
                                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelTEAMenuLayout.createSequentialGroup()
                                        .addComponent(btnTea2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(174, 174, 174)
                                        .addComponent(btnTea3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelTEAMenuLayout.createSequentialGroup()
                                        .addComponent(btnTea5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTea6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelTEAMenuLayout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBLACK)
                                    .addComponent(priceTEA1))
                                .addGap(347, 347, 347)
                                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelGREEN)
                                    .addComponent(priceTEA2))
                                .addGap(354, 354, 354)
                                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceTEA3)
                                    .addComponent(labelGINGER))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                    .addGroup(panelTEAMenuLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLEMON)
                            .addComponent(priceTEA4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMINT)
                            .addComponent(priceTEA5))
                        .addGap(313, 313, 313)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSTRAWBERRY)
                            .addComponent(priceTEA6))
                        .addGap(130, 130, 130)))
                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCART2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBACK2))
                .addGap(150, 150, 150))
        );
        panelTEAMenuLayout.setVerticalGroup(
            panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTEAMenuLayout.createSequentialGroup()
                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTEAMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCART2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTEAMenuLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTea2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTea1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTea3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTEAMenuLayout.createSequentialGroup()
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBLACK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGREEN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGINGER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTEA3)
                            .addComponent(priceTEA2)
                            .addComponent(priceTEA1))
                        .addGap(35, 35, 35)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTea5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTea6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTea4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLEMON, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMINT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSTRAWBERRY, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTEAMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTEA5)
                            .addComponent(priceTEA4)
                            .addComponent(priceTEA6)))
                    .addComponent(btnBACK2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        tpaneMenu.addTab("TEA", panelTEAMenu);

        btnPastry1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-croissant-100.png")); // NOI18N
        btnPastry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastry1ActionPerformed(evt);
            }
        });

        btnPastry2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-muffin-100.png")); // NOI18N
        btnPastry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastry2ActionPerformed(evt);
            }
        });

        btnPastry3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-cookies-100.png")); // NOI18N
        btnPastry3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastry3ActionPerformed(evt);
            }
        });

        btnPastry4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-brownies-100.png")); // NOI18N
        btnPastry4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastry4ActionPerformed(evt);
            }
        });

        btnPastry5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-cinnamon-roll-100.png")); // NOI18N
        btnPastry5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastry5ActionPerformed(evt);
            }
        });

        btnPastry6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\icons8-egg-tart-100.png")); // NOI18N
        btnPastry6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastry6ActionPerformed(evt);
            }
        });

        labelCROSSAINT.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelCROSSAINT.setText("CROSSAINT");

        labelMUFFIN.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelMUFFIN.setText("MUFFIN");

        labelTART.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelTART.setText("TARTS");

        labelCOOKIE.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelCOOKIE.setText("COOKIES");

        labelBROWNIES.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelBROWNIES.setText("BROWNIES");

        labelCINROLL.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        labelCINROLL.setText("CINNAMON ROLL");

        btnCART3.setBackground(new java.awt.Color(255, 153, 51));
        btnCART3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronia\\Downloads\\CART (2).jpg")); // NOI18N
        btnCART3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCART3ActionPerformed(evt);
            }
        });

        btnBACK3.setBackground(new java.awt.Color(51, 153, 255));
        btnBACK3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBACK3.setText("BACK");
        btnBACK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACK3ActionPerformed(evt);
            }
        });

        pricePTY1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pricePTY1.setText("₱ 25.00");

        pricePTY2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pricePTY2.setText("₱ 20.00");

        pricePTY3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pricePTY3.setText("₱ 8.00");

        pricePTY4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pricePTY4.setText("₱ 12.00");

        pricePTY5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pricePTY5.setText("₱ 30.00");

        pricePTY6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pricePTY6.setText("₱ 11.00");

        javax.swing.GroupLayout panelPASTRYMenuLayout = new javax.swing.GroupLayout(panelPASTRYMenu);
        panelPASTRYMenu.setLayout(panelPASTRYMenuLayout);
        panelPASTRYMenuLayout.setHorizontalGroup(
            panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCROSSAINT)
                    .addComponent(pricePTY1))
                .addGap(367, 367, 367)
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMUFFIN)
                    .addComponent(pricePTY2))
                .addGap(380, 380, 380)
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricePTY3)
                    .addComponent(labelCOOKIE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPASTRYMenuLayout.createSequentialGroup()
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPastry4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPastry1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                                .addComponent(btnPastry2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(btnPastry3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                                .addComponent(btnPastry5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPastry6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBROWNIES)
                            .addComponent(pricePTY4))
                        .addGap(332, 332, 332)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCINROLL)
                            .addComponent(pricePTY5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTART)
                            .addComponent(pricePTY6))
                        .addGap(105, 105, 105)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBACK3)
                    .addComponent(btnCART3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );
        panelPASTRYMenuLayout.setVerticalGroup(
            panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPastry3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPastry2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPastry1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCART3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                            .addComponent(labelCROSSAINT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pricePTY1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPastry4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                            .addComponent(labelMUFFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(pricePTY2)
                            .addGap(37, 37, 37)
                            .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPastry6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPastry5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                        .addComponent(labelCOOKIE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pricePTY3)))
                .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPASTRYMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCINROLL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelBROWNIES, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelTART, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPASTRYMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pricePTY4)
                                .addComponent(pricePTY5))
                            .addComponent(pricePTY6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPASTRYMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnBACK3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );

        tpaneMenu.addTab("PASTRY", panelPASTRYMenu);

        btnBACK4.setBackground(new java.awt.Color(51, 153, 255));
        btnBACK4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBACK4.setText("BACK");
        btnBACK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACK4ActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(153, 255, 153));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPayment.setText("PAY HERE");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelCARTLayout = new javax.swing.GroupLayout(panelCART);
        panelCART.setLayout(panelCARTLayout);
        panelCARTLayout.setHorizontalGroup(
            panelCARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCARTLayout.createSequentialGroup()
                .addGroup(panelCARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCARTLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(btnBACK4))
                    .addGroup(panelCARTLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        panelCARTLayout.setVerticalGroup(
            panelCARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCARTLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelCARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCARTLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCARTLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBACK4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );

        tpaneMenu.addTab("CART", panelCART);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tpaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1647, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMenuPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jMenuPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMenuPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tpaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeaActionPerformed
        tpaneMenu.setSelectedIndex(2);
    }//GEN-LAST:event_btnTeaActionPerformed

    private void btnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffeeActionPerformed
        tpaneMenu.setSelectedIndex(1);
    }//GEN-LAST:event_btnCoffeeActionPerformed

    private void btnPastryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastryActionPerformed
        tpaneMenu.setSelectedIndex(3);
    }//GEN-LAST:event_btnPastryActionPerformed

    private void btnCARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCARTActionPerformed
        tpaneMenu.setSelectedIndex(4);
    }//GEN-LAST:event_btnCARTActionPerformed

    private void btnCHKStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCHKStocksActionPerformed
        login loginFrame = new login();

        loginFrame.setVisible(true);
    }//GEN-LAST:event_btnCHKStocksActionPerformed

    private void btnCoffee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffee1ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnCoffee1ActionPerformed

    private void btnCoffee2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffee2ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnCoffee2ActionPerformed

    private void btnCoffee3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffee3ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnCoffee3ActionPerformed

    private void btnCoffee4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffee4ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnCoffee4ActionPerformed

    private void btnCoffee5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffee5ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnCoffee5ActionPerformed

    private void btnCoffee6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffee6ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnCoffee6ActionPerformed

    private void btnBACK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACK1ActionPerformed
        tpaneMenu.setSelectedIndex(0);
    }//GEN-LAST:event_btnBACK1ActionPerformed

    private void btnCART1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCART1ActionPerformed
        tpaneMenu.setSelectedIndex(4);
    }//GEN-LAST:event_btnCART1ActionPerformed

    private void btnTea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTea1ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnTea1ActionPerformed

    private void btnTea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTea2ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnTea2ActionPerformed

    private void btnTea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTea3ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnTea3ActionPerformed

    private void btnTea4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTea4ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnTea4ActionPerformed

    private void btnTea5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTea5ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnTea5ActionPerformed

    private void btnTea6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTea6ActionPerformed
        orderFrame.setVisible(true);
    }//GEN-LAST:event_btnTea6ActionPerformed

    private void btnBACK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACK2ActionPerformed
        tpaneMenu.setSelectedIndex(0);
    }//GEN-LAST:event_btnBACK2ActionPerformed

    private void btnCART2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCART2ActionPerformed
        tpaneMenu.setSelectedIndex(4);
    }//GEN-LAST:event_btnCART2ActionPerformed

    private void btnPastry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastry1ActionPerformed
        orderFrame2.setVisible(true);
    }//GEN-LAST:event_btnPastry1ActionPerformed

    private void btnPastry2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastry2ActionPerformed
        orderFrame2.setVisible(true);
    }//GEN-LAST:event_btnPastry2ActionPerformed

    private void btnPastry3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastry3ActionPerformed
        orderFrame2.setVisible(true);
    }//GEN-LAST:event_btnPastry3ActionPerformed

    private void btnPastry4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastry4ActionPerformed
        orderFrame2.setVisible(true);
    }//GEN-LAST:event_btnPastry4ActionPerformed

    private void btnPastry5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastry5ActionPerformed
        orderFrame2.setVisible(true);
    }//GEN-LAST:event_btnPastry5ActionPerformed

    private void btnPastry6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastry6ActionPerformed
        orderFrame2.setVisible(true);
    }//GEN-LAST:event_btnPastry6ActionPerformed

    private void btnCART3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCART3ActionPerformed
        tpaneMenu.setSelectedIndex(4);
    }//GEN-LAST:event_btnCART3ActionPerformed

    private void btnBACK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACK3ActionPerformed
        tpaneMenu.setSelectedIndex(0);
    }//GEN-LAST:event_btnBACK3ActionPerformed

    private void btnBACK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACK4ActionPerformed
        tpaneMenu.setSelectedIndex(0);
    }//GEN-LAST:event_btnBACK4ActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        
    }//GEN-LAST:event_btnPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBACK1;
    private javax.swing.JButton btnBACK2;
    private javax.swing.JButton btnBACK3;
    private javax.swing.JButton btnBACK4;
    private javax.swing.JButton btnCART;
    private javax.swing.JButton btnCART1;
    private javax.swing.JButton btnCART2;
    private javax.swing.JButton btnCART3;
    private javax.swing.JButton btnCHKStocks;
    private javax.swing.JButton btnCoffee;
    private javax.swing.JButton btnCoffee1;
    private javax.swing.JButton btnCoffee2;
    private javax.swing.JButton btnCoffee3;
    private javax.swing.JButton btnCoffee4;
    private javax.swing.JButton btnCoffee5;
    private javax.swing.JButton btnCoffee6;
    private javax.swing.JButton btnPastry;
    private javax.swing.JButton btnPastry1;
    private javax.swing.JButton btnPastry2;
    private javax.swing.JButton btnPastry3;
    private javax.swing.JButton btnPastry4;
    private javax.swing.JButton btnPastry5;
    private javax.swing.JButton btnPastry6;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnTea;
    private javax.swing.JButton btnTea1;
    private javax.swing.JButton btnTea2;
    private javax.swing.JButton btnTea3;
    private javax.swing.JButton btnTea4;
    private javax.swing.JButton btnTea5;
    private javax.swing.JButton btnTea6;
    private javax.swing.JPanel jMenuPanel1;
    private javax.swing.JPanel jMenuPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lPLEASE;
    private javax.swing.JLabel lWELCOME;
    private javax.swing.JLabel labelAMERICANO;
    private javax.swing.JLabel labelBLACK;
    private javax.swing.JLabel labelBROWNIES;
    private javax.swing.JLabel labelCAPPUCCINO;
    private javax.swing.JLabel labelCINROLL;
    private javax.swing.JLabel labelCOOKIE;
    private javax.swing.JLabel labelCROSSAINT;
    private javax.swing.JLabel labelCoffee;
    private javax.swing.JLabel labelESPRESSO;
    private javax.swing.JLabel labelGINGER;
    private javax.swing.JLabel labelGREEN;
    private javax.swing.JLabel labelLATTE;
    private javax.swing.JLabel labelLEMON;
    private javax.swing.JLabel labelMACCHIATO;
    private javax.swing.JLabel labelMINT;
    private javax.swing.JLabel labelMOCHA;
    private javax.swing.JLabel labelMUFFIN;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelPastry;
    private javax.swing.JLabel labelSTRAWBERRY;
    private javax.swing.JLabel labelTART;
    private javax.swing.JLabel labelTea;
    private javax.swing.JPanel panelCART;
    private javax.swing.JPanel panelCOFFEEMenu;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPASTRYMenu;
    private javax.swing.JPanel panelTEAMenu;
    private javax.swing.JLabel priceCOF1;
    private javax.swing.JLabel priceCOF2;
    private javax.swing.JLabel priceCOF3;
    private javax.swing.JLabel priceCOF4;
    private javax.swing.JLabel priceCOF5;
    private javax.swing.JLabel priceCOF6;
    private javax.swing.JLabel pricePTY1;
    private javax.swing.JLabel pricePTY2;
    private javax.swing.JLabel pricePTY3;
    private javax.swing.JLabel pricePTY4;
    private javax.swing.JLabel pricePTY5;
    private javax.swing.JLabel pricePTY6;
    private javax.swing.JLabel priceTEA1;
    private javax.swing.JLabel priceTEA2;
    private javax.swing.JLabel priceTEA3;
    private javax.swing.JLabel priceTEA4;
    private javax.swing.JLabel priceTEA5;
    private javax.swing.JLabel priceTEA6;
    private javax.swing.JTabbedPane tpaneMenu;
    // End of variables declaration//GEN-END:variables

    
}